{
 "title": "DashboardPrincipal",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Distancia leída por la Unidad 37A",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Distancia",
     "measurement": "unit_data",
     "select": [
      [
       { "params": [ "distance_cm" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=", "value": "37" },
      { "condition": "AND", "key": "unit_id::tag", "operator": "=", "value": "A" }
     ]
    }
   ]
  },
  {
   "title": "Distribución actual de Estados",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 9, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Libre",
     "groupBy": [
      { "params": [ "libre_count::field" ], "type": "tag" }
     ],
     "measurement": "summaries",
     "query": "SELECT \"libre_count\" FROM \"summaries\" WHERE (\"summary_type\"::tag = 'current_state_distribution') AND $timeFilter",
     "select": [
      [
       { "params": [ "libre_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "summary_type::tag", "operator": "=", "value": "current_state_distribution" }
     ]
    },
    {
     "alias": "Potencialmente libre",
     "measurement": "summaries",
     "query": "SELECT \"potencialmente_libre_count\" FROM \"summaries\" WHERE (\"summary_type\"::tag = 'current_state_distribution') AND $timeFilter",
     "select": [
      [
       { "params": [ "potencialmente_libre_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "summary_type::tag", "operator": "=", "value": "current_state_distribution" }
     ]
    },
    {
     "alias": "Ocupado",
     "measurement": "summaries",
     "query": "SELECT \"libre_count\" FROM \"summaries\" WHERE (\"summary_type\"::tag = 'current_state_distribution') AND $timeFilter",
     "select": [
      [
       { "params": [ "ocupado_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "summary_type::tag", "operator": "=", "value": "current_state_distribution" }
     ]
    }
   ]
  },
  {
   "title": "Estado de las Unidades del Nodo 37",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "Unidad A",
     "measurement": "unit_data",
     "query": "SELECT \"state\" FROM \"unit_data\" WHERE (\"node_id\"::tag = '37' AND \"unit_id\"::tag = 'A') AND $timeFilter",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=", "value": "37" },
      { "condition": "AND", "key": "unit_id::tag", "operator": "=", "value": "A" }
     ]
    },
    {
     "alias": "Unidad B",
     "measurement": "unit_data",
     "query": "SELECT \"state\" FROM \"unit_data\" WHERE (\"node_id\"::tag = '37' AND \"unit_id\"::tag = 'B') AND $timeFilter",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=", "value": "37" },
      { "condition": "AND", "key": "unit_id::tag", "operator": "=", "value": "A" }
     ]
    },
    {
     "alias": "Unidad C",
     "measurement": "unit_data",
     "query": "SELECT \"state\" FROM \"unit_data\" WHERE (\"node_id\"::tag = '37' AND \"unit_id\"::tag = 'C') AND $timeFilter",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=", "value": "37" },
      { "condition": "AND", "key": "unit_id::tag", "operator": "=", "value": "A" }
     ]
    },
    {
     "alias": "Unidad D",
     "measurement": "unit_data",
     "query": "SELECT \"state\" FROM \"unit_data\" WHERE (\"node_id\"::tag = '37' AND \"unit_id\"::tag = 'D') AND $timeFilter",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node_id::tag", "operator": "=", "value": "37" },
      { "condition": "AND", "key": "unit_id::tag", "operator": "=", "value": "A" }
     ]
    }
   ]
  }
 ]
}